## Uncomment by removing the '#' character in front of them to enable these ##
#output_name: "output"
#base_icon_state: "icon"

center_y: 6

prefabs:
 0: 0
 1: 1
 2: 2
 3: 3
 4: 4
 5: 5
 6: 6
 7: 7
 8: 8
 9: 9
 10: 10
 11: 11
 12: 12
 13: 13
 14: 14
 15: 15

se_convex: 0
nw_convex: 0
ne_convex: 0
sw_convex: 0

se_concave: 15
nw_concave: 15
ne_concave: 15
sw_concave: 15

se_horizontal: 12
nw_horizontal: 12
ne_horizontal: 12
sw_horizontal: 12

se_vertical: 3
nw_vertical: 3
ne_vertical: 3
sw_vertical: 3
