## PATH CONFIGS ##
#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#
#The path of the file to open.
#png support only for now.
file_to_open: "./color_input.png"

#Name for the file to output and the icon-state prefixes.
#Example output with "wall" as input: "wall.dmi" -> wall-0, wall-63, wall-137...
#Keep this name different from the input one if you don't have it backed up to avoid losing the old file.
output_name: "color-output"
#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#


## ICON CONFIGS ##
#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#
#Possible icon coordinates here range from (0,0) in the top-left corner to (icon_size_x,icon_size_y) in the bottom-right one.
icon_size_x: 32
icon_size_y: 32

#Top-down sprites are centered in the middle: (16,16) for a 32x32 tile.
#The same is not true in the Y axis for 3/4 walls in general, with the center being elevated by the perspective.
center_x: 16
center_y: 6
#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#


## COORDINATE CONFIGS ##
#These coordinates are in icon-sized steps, according to the input image.
#The top-left icon is in coordinates (0,0).
#The maximum valid x value is ((pixel-width / icon_size_x) - 1).
#The maximum valid y value is ((pixel-height / icon_size_y) - 1).
#This means that a hypothetical rectangle with 3x2 sprites, 3 in the x-axis and 2 in the y, will range from coordinates (0,0) to (2,1).

#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#

##Pre-fabricated icons in case we want some of them to look a particular way, instead of having them assembled by the generic corners.
#This config is optional.
#The key is as follows, inside of the prefabs group:
# Key:
##Key here is a number index from 0 to 255, representing the bitflags that mark the wall combination.
#  x: coordinate
## The x coordinate in icon-sized steps, as defined above.
#  y: coordinate
## The y coordinate in icon-sized steps, as defined above.

prefabs:
#Purely convex icon, all corners are convex.
 0:
  x: 3
  y: 3
 1:
  x: 3
  y: 2
 2:
  x: 3
  y: 0
#Purely vertical icon, all corners are vertical.
 3:
  x: 3
  y: 1
 4:
  x: 0
  y: 3
 5:
  x: 0
  y: 2
 6:
  x: 0
  y: 0
 7:
  x: 0
  y: 1
 8:
  x: 2
  y: 3
 9:
  x: 2
  y: 2
 10:
  x: 2
  y: 0
 11:
  x: 2
  y: 1
#Purely horizontal icon, all corners are horizontal.
 12:
  x: 1
  y: 3
 13:
  x: 1
  y: 2
 14:
  x: 1
  y: 0
 15:
  x: 1
  y: 1
 21:
  x: 4
  y: 2
 38:
  x: 4
  y: 0
 55:
  x: 4
  y: 1
 74:
  x: 6
  y: 0
 110:
  x: 5
  y: 0
 137:
  x: 6
  y: 2
 157:
  x: 5
  y: 2
 203:
  x: 6
  y: 1
#Purely flat icon, all corners are flat.
 255:
  x: 5
  y: 1


##Standard corners.
#These configs are necessary to be able to run the program.

#Convex corners.
se_convex_x: 3
se_convex_y: 3
nw_convex_x: 3
nw_convex_y: 3
ne_convex_x: 3
ne_convex_y: 3
sw_convex_x: 3
sw_convex_y: 3

#Concave corners.
se_concave_x: 0
se_concave_y: 0
nw_concave_x: 2
nw_concave_y: 2
ne_concave_x: 0
ne_concave_y: 2
sw_concave_x: 2
sw_concave_y: 0

#Horizontal corners.
se_horizontal_x: 0
se_horizontal_y: 3
nw_horizontal_x: 2
nw_horizontal_y: 3
ne_horizontal_x: 0
ne_horizontal_y: 3
sw_horizontal_x: 2
sw_horizontal_y: 3

#Vertical corners.
se_vertical_x: 3
se_vertical_y: 0
nw_vertical_x: 3
nw_vertical_y: 2
ne_vertical_x: 3
ne_vertical_y: 2
sw_vertical_x: 3
sw_vertical_y: 0

#Flat corners.
se_flat_x: 4
se_flat_y: 0
nw_flat_x: 6
nw_flat_y: 2
ne_flat_x: 4
ne_flat_y: 2
sw_flat_x: 6
sw_flat_y: 0

#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#


## DEBUG CONFIGS ##
#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#
#If enabled, it will produce an image with every possible corner type variant (convex, concave, horizontal, vertical and flat).
#Useful for debugging purposes.
#This config is optional.
produce_corners: false
#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#

## VERSION CONFIGS ##
#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#v#
#These config is necessary to be able to run the program.
dmi_version: "4.0"
#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#^#